name: Deploy to Cloud Run

on:
  push:
    branches:
      - "group-*" # only deploy branches like group-01, group-07
  workflow_dispatch: # allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"

      - name: Deploy to Cloud Run
        env:
          REGION: ${{ secrets.GCP_REGION }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          SERVICE: recipes-${{ github.ref_name }} # e.g. recipes-group-07
          GROUP_ID: ${{ github.ref_name }} # pass branch name as group id
        run: |
          echo "🚀 Deploying branch $GROUP_ID as Cloud Run service $SERVICE"

          # Build & deploy from source using buildpacks
          gcloud run deploy "$SERVICE" \
            --source . \
            --region "$REGION" \
            --project "$PROJECT_ID" \
            --service-account=recipes-runtime@$PROJECT_ID.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --max-instances=1 --min-instances=0 \
            --set-env-vars=GROUP_ID="$GROUP_ID",FUNCTION_BASE_URL="${{ secrets.FUNCTION_BASE_URL }}" \
            --set-secrets=GCP_SA_JSON=MCP_INVOKER_JSON:latest
